<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Winnow.Data\Winnow.Data.csproj" />
    <ProjectReference Include="..\..\src\Winnow.Recommend\Winnow.Recommend.csproj" />
  </ItemGroup>
</Project>
